name: 🚀 Deploy to Production

on: 
  push: 
    branches:
      - master

jobs: 
  build:
    name: 📂 Build artifact  
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2

        name: Installing dependencies
        run: npm ci

      - name: 🚚 Build project
        run: npm run build
      
      - name: 📂 Creating deployment artifact
        env: 
          GITHUB_SHA: ${{  github.sha  }}
        run: tar -czf build.tgz "${GITHUB_SHA}".tar.gz build/
      
      - name: 📂 Storing artifact
        uses: actions/upload-artifact@v2
        with: 
          name: app-build
          path: ${{ github.sha }}.tar.gz